name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies for backend
        run: |
          cd server
          npm install

      - name: Install dependencies for frontend
        run: |
          cd public
          npm install

      - name: Run tests for backend
        run: |
          cd server
          npm test

      - name: Run tests for frontend
        run: |
          cd public
          npm test

      - name: Build Docker images for frontend and backend
        run: |
          docker build -t daivecode/snappy-frontend:${{ github.sha }} -f public/Dockerfile ./public
          docker build -t daivecode/snappy-backend:${{ github.sha }} -f server/Dockerfile ./server

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to DockerHub
        run: |
          docker push daivecode/snappy-frontend:${{ github.sha }}
          docker push daivecode/snappy-backend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker images
        run: |
          docker pull daivecode/snappy-frontend:${{ github.sha }}
          docker pull daivecode/snappy-backend:${{ github.sha }}

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml up -d

  deploy_test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker images
        run: |
          docker pull daivecode/snappy-frontend:${{ github.sha }}
          docker pull daivecode/snappy-backend:${{ github.sha }}

      - name: Deploy to test environment with Docker Compose
        run: |
          docker-compose -f docker-compose.yml down
          docker-compose -f docker-compose.yml -p test up -d
